### ISSUE TITLE
Cannot read property '_unzip' of undefined

### ISSUE THREAD

**Issue by gnujeremie** [Tjatse/req-fast#4]
Hi,

I just updated to the latest version, because I was getting an error like : 
```
unexpected end of file     at Zlib._handle.onerror
```
which you just fixed, and now I am getting the following error using req-fast (in fact it's using read-art, which is using req-fast :))  : 

```
/Users/jeremie/Documents/Workspace/AAA/Apps/aaa/node_modules/req-fast/lib/req_stream.js:117
          if (this._unzip) {
                  ^

TypeError: Cannot read property '_unzip' of undefined
    at shouldContinue (/Users/jeremie/Documents/Workspace/AAA/Apps/aaa/node_modules/req-fast/lib/req_stream.js:117:19)
    at RequestStream.onEnd (/Users/jeremie/Documents/Workspace/AAA/Apps/aaa/node_modules/req-fast/lib/req_stream.js:163:14)
    at emitNone (events.js:72:20)
    at IncomingMessage.emit (events.js:166:7)
    at endReadableNT (_stream_readable.js:905:12)
    at doNTCallback2 (node.js:452:9)
    at process._tickCallback (node.js:366:17)
Program node bin/www exited with code 1
```

**Comment by gnujeremie** [comment]
I quickly fixed by adding 
```
if (!this) {
    return;
}
```
just before line 117 (waiting for your 'official' fix), and now I get again
```
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: unexpected end of file
    at Zlib._handle.onerror (zlib.js:363:17)
Program node bin/www exited with code 1
```

**Comment by Tjatse** [comment]
Oh, I am working on the Inflate/InflateRaw, and made a mistake on the context of functions.
Please install the v0.2.12 and try again, everything should goes fine now.

If you have any idea on how to automatic switch between `Inflate` and `InflateRaw`, help me out.

**Comment by Tjatse** [comment]
BTW, whats the link you are crawling?

**Comment by gnujeremie** [comment]
Thanks for the quick answer !
I now get the following error : 
```
/Users/jeremie/Documents/Workspace/AAA/Apps/aaa/node_modules/req-fast/lib/req_stream.js:145
        o.removeAllListeners();
          ^

TypeError: o.removeAllListeners is not a function
    at RequestStream.onError (/Users/jeremie/Documents/Workspace/AAA/Apps/aaa/node_modules/req-fast/lib/req_stream.js:145:11)
    at RequestStream.shouldContinue (/Users/jeremie/Documents/Workspace/AAA/Apps/aaa/node_modules/req-fast/lib/req_stream.js:121:30)
    at RequestStream.onEnd (/Users/jeremie/Documents/Workspace/AAA/Apps/aaa/node_modules/req-fast/lib/req_stream.js:163:29)
    at emitNone (events.js:72:20)
    at IncomingMessage.emit (events.js:166:7)
    at endReadableNT (_stream_readable.js:905:12)
    at doNTCallback2 (node.js:452:9)
    at process._tickCallback (node.js:366:17)
Program node bin/www exited with code 1
```

I'm trying to see if I can find which link is the problem, because I am crawling many in parallel (and I don't know yet which breaks the program.... I'm pretty new to nodejs).

**Comment by Tjatse** [comment]
You're welcome, I'm seeking a specific case to test `Inflate` / `InflateRaw`, your situation helps me expedite it.
I've publish `v0.2.12-rc1`, so try to update `req-fast` to `0.2.12-rc1`, and let me know the result.

**Comment by gnujeremie** [comment]
I get again
```
/Users/jeremie/Documents/Workspace/AAA/Apps/aaa/node_modules/read-art/node_modules/req-fast/lib/req_stream.js:117
          if (this._unzip) {
                  ^

TypeError: Cannot read property '_unzip' of undefined
    at shouldContinue (/Users/jeremie/Documents/Workspace/AAA/Apps/aaa/node_modules/read-art/node_modules/req-fast/lib/req_stream.js:117:19)
    at RequestStream.onEnd (/Users/jeremie/Documents/Workspace/AAA/Apps/aaa/node_modules/read-art/node_modules/req-fast/lib/req_stream.js:163:14)
    at emitNone (events.js:72:20)
    at IncomingMessage.emit (events.js:166:7)
    at endReadableNT (_stream_readable.js:905:12)
    at doNTCallback2 (node.js:452:9)
    at process._tickCallback (node.js:366:17)
Program node bin/www exited with code 1
```

I'm up to date... I'm trying to find the guilty url :)

**Comment by gnujeremie** [comment]
Hold on a second, I just noticed I have node_module/req-fast and node_module/read-art/node_module/req-fast...

**Comment by gnujeremie** [comment]
Okay so now I'm back with
```
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: unexpected end of file
    at Zlib._handle.onerror (zlib.js:363:17)
Program node bin/www exited with code 1
```

Sorry for the previous message ^^'

**Comment by Tjatse** [comment]
Thanks a lot, you can simply get rid of this by setting `disableGzip` to `true`, e..g.:
```javascript
var read = require('read-art');
read({
  uri: 'http://www.example.com',
  disableGzip: true
}, function(){})
```
But I strongly hope you can find out the unordinary link which will cause  the crash of `zlib` ;)!

**Comment by gnujeremie** [comment]
Thanks for your replies :)
Stupid question, but what does disabling gzip mean ? Pages content will then be unreadable (for the gzipped ones at least) ?
