### ISSUE TITLE
Webpack causing issues

### ISSUE THREAD

**Issue by rw3iss** [Tjatse/req-fast#9]
```
ERROR in ./~/tunnel2/lib/tunnel.js
Module not found: Error: Cannot resolve module 'net' in /web/sites/tripora/node_modules/tunnel2/lib
 @ ./~/tunnel2/lib/tunnel.js 3:10-24

ERROR in ./~/tunnel2/lib/tunnel.js
Module not found: Error: Cannot resolve module 'tls' in /web/sites/tripora/node_modules/tunnel2/lib
 @ ./~/tunnel2/lib/tunnel.js 4:10-24

ERROR in ./~/iconv-lite/encodings/tables/gb18030-ranges.json
Module parse failed: /web/sites/tripora/node_modules/iconv-lite/encodings/tables/gb18030-ranges.json Unexpected token (1:9)
You may need an appropriate loader to handle this file type.
SyntaxError: Unexpected token (1:9)
    at Parser.pp$4.raise (/web/sites/tripora/node_modu```
ERROR in ./~/tunnel2/lib/tunnel.js
Module not found: Error: Cannot resolve module 'net' in /web/sites/example/node_modules/tunnel2/lib
 @ ./~/tunnel2/lib/tunnel.js 3:10-24

ERROR in ./~/tunnel2/lib/tunnel.js
Module not found: Error: Cannot resolve module 'tls' in /web/sites/example/node_modules/tunnel2/lib
 @ ./~/tunnel2/lib/tunnel.js 4:10-24

ERROR in ./~/iconv-lite/encodings/tables/gb18030-ranges.json
Module parse failed: /web/sites/example/node_modules/iconv-lite/encodings/tables/gb18030-ranges.json Unexpected token (1:9)
You may need an appropriate loader to handle this file type.
SyntaxError: Unexpected token (1:9)
    at Parser.pp$4.raise (/web/sites/example/node_modules/webpack/node_modules/acorn/dist/acorn.js:2221:15)
    at Parser.pp.unexpected (/web/sites/example/node_modules/webpack/node_modules/acorn/dist/acorn.js:603:10)
    at Parser.pp.semicolon (/web/sites/example/node_modules/webpack/node_modules/acorn/dist/acorn.js:581:61)
    at Parser.pp$1.parseExpressionStatement (/web/sites/example/node_modules/webpack/node_modules/acorn/dist/acorn.js:966:10)
    at Parser.pp$1.parseStatement (/web/sites/example/node_modules/webpack/node_modules/acorn/dist/acorn.js:730:24)
    at Parser.pp$1.parseBlock (/web/sites/example/node_modules/webpack/node_modules/acorn/dist/acorn.js:981:25)
    at Parser.pp$1.parseStatement (/web/sites/example/node_modules/webpack/node_modules/acorn/dist/acorn.js:709:33)
    at Parser.pp$1.parseTopLevel (/web/sites/example/node_modules/webpack/node_modules/acorn/dist/acorn.js:638:25)
    at Parser.parse (/web/sites/example/node_modules/webpack/node_modules/acorn/dist/acorn.js:516:17)
    at Object.parse (/web/sites/example/node_modules/webpack/node_modules/acorn/dist/acorn.js:3098:39)
 @ ./~/iconv-lite/encodings/dbcs-data.js 99:37-76
```les/webpack/node_modules/acorn/dist/acorn.js:2221:15)
    at Parser.pp.unexpected (/web/sites/tripora/node_modules/webpack/node_modules/acorn/dist/acorn.js:603:10)
    at Parser.pp.semicolon (/web/sites/tripora/node_modules/webpack/node_modules/acorn/dist/acorn.js:581:61)
    at Parser.pp$1.parseExpressionStatement (/web/sites/tripora/node_modules/webpack/node_modules/acorn/dist/acorn.js:966:10)
    at Parser.pp$1.parseStatement (/web/sites/tripora/node_modules/webpack/node_modules/acorn/dist/acorn.js:730:24)
    at Parser.pp$1.parseBlock (/web/sites/tripora/node_modules/webpack/node_modules/acorn/dist/acorn.js:981:25)
    at Parser.pp$1.parseStatement (/web/sites/tripora/node_modules/webpack/node_modules/acorn/dist/acorn.js:709:33)
    at Parser.pp$1.parseTopLevel (/web/sites/tripora/node_modules/webpack/node_modules/acorn/dist/acorn.js:638:25)
    at Parser.parse (/web/sites/tripora/node_modules/webpack/node_modules/acorn/dist/acorn.js:516:17)
    at Object.parse (/web/sites/tripora/node_modules/webpack/node_modules/acorn/dist/acorn.js:3098:39)
 @ ./~/iconv-lite/encodings/dbcs-data.js 99:37-76
```

**Comment by Tjatse** [comment]
This module only works for node.js server, sorry, dude.

**Comment by rw3iss** [comment]
Heh realized.. <--noob. Cheers.
